dist: bionic
language: bash
git:
  depth: false
addons:
  apt:
    update: true
    packages:
    # LaTeX decent font processor
    - cm-super
    # For Minted
    - python-pygments
    # LaTeX
    - texlive-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-fonts-recommended
    # Biber replacement for BibLaTeX
    - biber
    # Debug
    - tree
env:
  global:
    - TERM="dumb"
install:
  - curl -s "https://get.sdkman.io" | bash
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install kotlin
  - sdk install kscript
script:
  - ./build.kts
after_failure:
  - tree -a
  - cat texput.log
before_deploy:
  - git config --local user.name "Danilo Pianini"
  - git config --local user.email "danilo.pianini@unibo.it"
  - if [[ $(git describe) == *"-"* ]]; then git tag $(git describe) || :; fi
deploy:
  - provider: releases
    api_key:
      secure: BykD5IfX5Wb3Qg3XblenNtMDRIpRtNS//d70pwLSm4n1h1BOn5e1JOhB/jZlI8LMVvpFYptZXDfG2XhXr/Hsy7VakVetXnvct1UK+iJpTmal/D7rJ925cTmdL6FtfdJE0h7QrM49oA1tFcXTGROf/ZWcSSsofFLcF67RAbMLV05CvUaKtU5zUgNdfT8d6iDZ0UjERuaVOw22pJ26KeLCVh7T5bCU4uuh0U0wmAk6SCoIIviBO6RCQLtIJLE5mwhJGWkxILW0zFIxzfyKWMKUFTDrltDsipZ59yx1VfD7bnm9xUp0RkVs0I5u/IWoZQehAe2olYABA093BT2SH7CngdtPari84NYWmVDXc5DTRkh2iY1nsUT6IYzGhxI/AGR5tSGP387C9YYIfg5QCr/Xxj/nGiZIMcQHK+rVINYpSdNGFCQ9pqcYqTsnk2jE9uTSaZd8gMFtTJaviVWVuWGxLsu6sLJVHecKbgICD+obACNgUrEmO5zTAd4BHrgXw0PM3KKRTlbAnil/G225GCdPRd6KRcq3lwCLVXdWFoNwMHXIGbjV1EiZ1hPxIo+YJr/ak7289MkZJXn2th9qXP1U7Y0J8eXPLj13KLPZIiHW8UrIs41OsdRzpbaQuSgXyriYrUbgWHBYbxXCB9o9WEly17COtVQ7fU7M5qNZ/bbjkpw=
    file_glob: true
    file: "${TRAVIS_BUILD_DIR}/erc-*/*.pdf"
    skip_cleanup: true
    on:
      repo: DanySK/erc-latex-template
      tags: true
  - provider: releases
    api_key:
      secure: BykD5IfX5Wb3Qg3XblenNtMDRIpRtNS//d70pwLSm4n1h1BOn5e1JOhB/jZlI8LMVvpFYptZXDfG2XhXr/Hsy7VakVetXnvct1UK+iJpTmal/D7rJ925cTmdL6FtfdJE0h7QrM49oA1tFcXTGROf/ZWcSSsofFLcF67RAbMLV05CvUaKtU5zUgNdfT8d6iDZ0UjERuaVOw22pJ26KeLCVh7T5bCU4uuh0U0wmAk6SCoIIviBO6RCQLtIJLE5mwhJGWkxILW0zFIxzfyKWMKUFTDrltDsipZ59yx1VfD7bnm9xUp0RkVs0I5u/IWoZQehAe2olYABA093BT2SH7CngdtPari84NYWmVDXc5DTRkh2iY1nsUT6IYzGhxI/AGR5tSGP387C9YYIfg5QCr/Xxj/nGiZIMcQHK+rVINYpSdNGFCQ9pqcYqTsnk2jE9uTSaZd8gMFtTJaviVWVuWGxLsu6sLJVHecKbgICD+obACNgUrEmO5zTAd4BHrgXw0PM3KKRTlbAnil/G225GCdPRd6KRcq3lwCLVXdWFoNwMHXIGbjV1EiZ1hPxIo+YJr/ak7289MkZJXn2th9qXP1U7Y0J8eXPLj13KLPZIiHW8UrIs41OsdRzpbaQuSgXyriYrUbgWHBYbxXCB9o9WEly17COtVQ7fU7M5qNZ/bbjkpw=
    file_glob: true
    file: "${TRAVIS_BUILD_DIR}/erc-*/*.pdf"
    skip_cleanup: true
    on:
      repo: DanySK/erc-latex-template
      tags: false
